// snake_case error codes returned in { error: { code, message } } (contract section 1)
export const ErrorCodes = {
  VALIDATION: 'validation_error',
  NOT_FOUND: 'not_found',
  UNAUTHORIZED: 'unauthorized',
  FORBIDDEN: 'forbidden',
  CSRF_FAILED: 'csrf_failed',
  INTERNAL: 'internal_error',
  TOO_MANY_REQUESTS: 'too_many_requests',
  TOO_MANY_ATTEMPTS: 'too_many_attempts',
  INVALID_CREDENTIALS: 'invalid_credentials',
  INVALID_REFRESH: 'invalid_refresh',
  INVALID_TOKEN: 'invalid_token',
  EMAIL_NOT_VERIFIED: 'email_not_verified',
  PROJECT_LOCKED: 'project_locked',
  RENDER_IN_PROGRESS: 'render_in_progress',
  INVALID_STATUS: 'invalid_status',
  INVALID_URL: 'invalid_url',
  INVALID_AIRBNB_URL: 'invalid_airbnb_url',
  IMAGE_COUNT_INVALID: 'image_count_invalid',
  WATERMARK_PROCESSING: 'watermark_processing',
  QUOTA_EXCEEDED: 'quota_exceeded',
  INSUFFICIENT_CREDITS: 'insufficient_credits',
  PAYMENTS_UNAVAILABLE: 'payments_unavailable',
  INVALID_TIERS: 'invalid_tiers',
  RIGHTS_REQUIRED: 'rights_required',
  TITLE_REQUIRED: 'title_required',
  CONSENT_REQUIRED: 'consent_required',
  ATTEMPTS_EXHAUSTED: 'attempts_exhausted',
  ALREADY_PROCESSING: 'already_processing',
  NO_PROCESSED_VERSION: 'no_processed_version',
  VIDEO_NOT_READY: 'video_not_ready',
  NO_IMAGES: 'no_images',
  RENDERS_DISABLED: 'renders_disabled',
  DEWATERMARK_DISABLED: 'dewatermark_disabled',
  DEWATERMARK_UNAVAILABLE: 'dewatermark_unavailable',
  SCRAPE_DISABLED: 'scrape_disabled',
  SCRAPE_UNAVAILABLE: 'scrape_unavailable',
  STORAGE_UNAVAILABLE: 'storage_unavailable',
  STORAGE_ERROR: 'storage_error',
  QUEUE_UNAVAILABLE: 'queue_unavailable',
  TOO_MANY_IMAGES: 'too_many_images',
  INVALID_IMAGE_ORDER: 'invalid_image_order',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
