import type { FC } from "react";
import Link from "next/link";
import { Routes } from "@/routes/routes";
import { LegalLayout, LegalList, LegalSection } from "@/views/legal/components/legal-layout";

const TermsPage: FC = () => (
  <LegalLayout title="Terms of Service" updated="4 October 2026">
    <LegalSection heading="1. The service">
      <p>
        Reelty turns photos of a property into a short walkthrough video. You supply photos by uploading them or by pasting a
        listing link, choose and order the shots, and we generate an MP4 for you. The service is in beta and limited by a
        monthly video quota.
      </p>
    </LegalSection>

    <LegalSection heading="2. Your account">
      <p>
        You need an account to use Reelty. Keep your password private and use a real email address you can access. You are
        responsible for activity on your account. We may suspend accounts that abuse the service or its quotas.
      </p>
    </LegalSection>

    <LegalSection heading="3. Your photos and your rights">
      <p>
        Only use photos you own or have permission to use. Before your first render of each video you confirm this, and we
        store that confirmation together with the time and your account. If you paste a listing link, only do so for
        listings you are authorised to promote. Third-party sites and platforms, including Airbnb, may restrict automated
        access or copying of their content, and the photos are usually protected by copyright. That responsibility is yours.
      </p>
    </LegalSection>

    <LegalSection heading="4. Watermark removal">
      <p>
        You can run watermark removal on images you are entitled to edit. Removing someone else&apos;s watermark can infringe
        their rights. By using the feature you confirm that you have the right to edit the image, and you accept sole
        responsibility for the result and for how you use it. We keep the original image alongside any edited version.
      </p>
    </LegalSection>

    <LegalSection heading="5. AI-generated output">
      <p>
        Videos are generated by AI from your photos. They are illustrative and <strong>may differ from the real property</strong>:
        rooms, proportions, lighting, objects and surroundings can be altered or invented. Property advertising rules vary by
        country. You are responsible for checking that a video is accurate and lawful before you publish or share it, and for
        not presenting it as a faithful depiction of the property.
      </p>
    </LegalSection>

    <LegalSection heading="6. Music and content">
      <p>
        When music is on, the soundtrack is an original ambient track generated by Reelty. You may not upload content that is
        unlawful, infringing, or depicts people without their permission.
      </p>
    </LegalSection>

    <LegalSection heading="7. Quotas, refunds and availability">
      <LegalList
        items={[
          "Each account has a monthly video quota. A video that fails to render does not use up your quota, and failed renders are refunded.",
          "Only one video can be rendering at a time per account.",
          "Rendering depends on third-party providers. Delays and temporary outages can happen, and we show a clear status when they do.",
        ]}
      />
    </LegalSection>

    <LegalSection heading="8. Deleting your content">
      <p>
        You can delete a project at any time. Deleting removes its video, poster and every photo from our storage. Videos are
        kept until you delete them.
      </p>
    </LegalSection>

    <LegalSection heading="9. Liability">
      <p>
        The service is provided as is during beta. To the extent allowed by law, Reelty is not liable for indirect losses or for
        the way you use generated videos. Detailed liability terms will be added after legal review.
      </p>
    </LegalSection>

    <p className="text-sm text-muted-foreground">
      See also our{" "}
      <Link href={Routes.privacy} className="font-medium text-primary underline-offset-4 hover:underline">
        Privacy Policy
      </Link>
      .
    </p>
  </LegalLayout>
);

export default TermsPage;
