// Pure builder for the synthesised, original ambient pad (contract §5, spec §6).
// No third-party recording is involved: four chords of detuned sine "voices" with slow overlapping
// sin² envelopes, a low-pass and an echo tail. The 64 s result is loopable: the part of the last
// chord that would run past 64 s is generated again (same phase) at the very beginning.

export const SoundtrackSpec = {
  /** Length of the finished loop. Longer than the longest video (12 clips = 57.6 s). */
  loopSeconds: 64,
  chordSeconds: 32,
  chordStepSeconds: 16,
  sampleRate: 44100,
  bitrate: '192k',
} as const;

export const SOUNDTRACK_LICENSE_TEXT =
  'Generated by Reelty; dedicated to the public domain under CC0 1.0 Universal ' +
  '(https://creativecommons.org/publicdomain/zero/1.0/). No third-party material is included.\n';

// Cmaj9 -> Am9 -> Fmaj7 -> G6/9 (frequencies in Hz)
const CHORDS: number[][] = [
  [130.81, 196.0, 329.63, 493.88, 587.33],
  [110.0, 164.81, 261.63, 392.0, 493.88],
  [87.31, 130.81, 220.0, 329.63, 440.0],
  [98.0, 146.83, 246.94, 329.63, 440.0],
];

/** `tOffset` shifts the local time of the chord (used for the wrapped tail). */
function chordExpression(freqs: number[], side: 'L' | 'R', tOffset = 0): string {
  const tt = tOffset ? `(t+${tOffset})` : 't';
  const detune = side === 'L' ? [0.0, 0.31] : [0.17, -0.23];
  const terms: string[] = [];
  for (const f of freqs) {
    for (const d of detune) {
      terms.push(`sin(2*PI*${(f + d).toFixed(2)}*${tt})`);
    }
  }
  const window = `pow(sin(PI*${tt}/${SoundtrackSpec.chordSeconds}),2)`;
  const breathing = `(0.85+0.15*sin(2*PI*${side === 'L' ? '0.11' : '0.13'}*${tt}))`;
  return `0.045*${window}*${breathing}*(${terms.join('+')})`;
}

export function buildSoundtrackFilterGraph(): string {
  const { chordSeconds, chordStepSeconds, loopSeconds, sampleRate } = SoundtrackSpec;
  const parts: string[] = [];
  const labels: string[] = [];

  CHORDS.forEach((freqs, i) => {
    const expr = `${chordExpression(freqs, 'L')}|${chordExpression(freqs, 'R')}`;
    const ms = i * chordStepSeconds * 1000;
    parts.push(`aevalsrc=exprs='${expr}':s=${sampleRate}:d=${chordSeconds},adelay=${ms}|${ms}[c${i}]`);
    labels.push(`[c${i}]`);
  });

  // Wrapped tail: the last chord's second half (local time 16..32 s) restarts at 0 so the loop is seamless.
  const last = CHORDS.length - 1;
  const lastStart = last * chordStepSeconds; // 48
  const overrun = lastStart + chordSeconds - loopSeconds; // 16 s past the loop end
  const tailOffset = chordSeconds - overrun; // local time at which the loop end falls (16)
  const tailExpr = `${chordExpression(CHORDS[last], 'L', tailOffset)}|${chordExpression(CHORDS[last], 'R', tailOffset)}`;
  parts.push(`aevalsrc=exprs='${tailExpr}':s=${sampleRate}:d=${overrun}[ctail]`);
  labels.push('[ctail]');

  parts.push(
    `${labels.join('')}amix=inputs=${labels.length}:normalize=0:duration=longest,` +
      `atrim=0:${loopSeconds},asetpts=PTS-STARTPTS,` +
      'lowpass=f=2600,aecho=0.8:0.7:60|113|189:0.35|0.28|0.2,alimiter=limit=0.9,' +
      'aformat=sample_fmts=fltp:channel_layouts=stereo[out]',
  );
  return parts.join(';');
}

export function buildSoundtrackArgs(outFile: string): string[] {
  return [
    '-filter_complex', buildSoundtrackFilterGraph(),
    '-map', '[out]',
    '-t', String(SoundtrackSpec.loopSeconds),
    '-ar', String(SoundtrackSpec.sampleRate),
    '-c:a', 'libmp3lame',
    '-b:a', SoundtrackSpec.bitrate,
    outFile,
  ];
}
